import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { BookgameEngine } from "../src/engine/bookgame-engine.mjs";
import { compileStory } from "../src/compiler/story-compiler.mjs";
import { SaveStore } from "../src/engine/save-store.mjs";
import { createNewGameState } from "../src/engine/state.mjs";
import { SequenceDice } from "../src/engine/dice.mjs";
const scenesDir=fileURLToPath(new URL("../content/scenes/",import.meta.url));
const modulesDir=fileURLToPath(new URL("../content/modules/",import.meta.url));
const eventsDir=fileURLToPath(new URL("../content/events/",import.meta.url));
const ecologyProfilesDir=fileURLToPath(new URL("../content/ecology/",import.meta.url));
const zonePoolsFile=fileURLToPath(new URL("../../campaign/world/ecology/ZONE_POOLS.json",import.meta.url));
const distributionFile=fileURLToPath(new URL("../../campaign/world/ecology/SPECIES_DISTRIBUTION.json",import.meta.url));
const faunaIndexFile=fileURLToPath(new URL("../../campaign/world/fauna/ASTERIA_FAUNA_INDEX.json",import.meta.url));
const ecologyOptions={profilesDir:ecologyProfilesDir,zonePoolsFile,distributionFile,faunaIndexFile};
const fixedNow=()=> "2026-10-05T20:00:00.000Z";
async function makeEngine(dice=new SequenceDice([1])){const bundle=await compileStory({scenesDir,modulesDir,eventsDir,ecologyOptions});const scenes={async load(id){return structuredClone(bundle.scenes[id]);},async loadWorldEvents(){return structuredClone(bundle.worldEvents??[]);},async loadEcology(){return structuredClone(bundle.ecology);}};return {engine:new BookgameEngine({scenes,dice,now:fixedNow}),bundle};}
function active(minutes=240){const s=createNewGameState({protagonist:"Luke",now:fixedNow});s.competition.rank="D";s.competition.rankOrder=2;Object.assign(s.world.flags,{m1_complete:true,m02_unlocked:true,m2_active:true,m2_complete:true,m03_unlocked:true,m3_active:true,ferravia_discovered:true,ferrox_incident_started:true,old_maps_read:true,ferrox_rescue_access_known:true});s.quests.M3_FERROX_RESCUE={id:"M3_FERROX_RESCUE",title:"Emergenza",objective:"Rescue",status:"active",resolution:null,startedAtMinutes:s.world.elapsedMinutes,deadlineAtMinutes:s.world.elapsedMinutes+minutes,resolvedAtMinutes:null,onDeadline:{status:"failed",resolution:"rescue_window_missed",resolvedBy:"world"}};s.story.sceneId="m03-ferrox-rescue";s.story.nodeId="rescue_perimeter";s.world.locationId="ferrox_rescue_perimeter";return s;}
function failed(){const s=active();s.quests.M3_FERROX_RESCUE.status="failed";s.quests.M3_FERROX_RESCUE.resolution="rescue_window_missed";s.quests.M3_FERROX_RESCUE.resolvedAtMinutes=s.world.elapsedMinutes;s.world.flags.ferrox_rescue_state="missed";return s;}
test("M3_07 compiles with rescue checkpoint and terminal states",async()=>{const {bundle}=await makeEngine();const s=bundle.scenes["m03-ferrox-rescue"];assert.ok(s.nodes.rescue_checkpoint);assert.ok(s.nodes.rescue_success);assert.ok(s.nodes.rescue_missed);});
test("M3_07 active quest enters staging",async()=>{const {engine}=await makeEngine();let s=active();const v=await engine.present(s);assert.ok(v.choices.some(c=>c.id==="enter_live_rescue"));s=await engine.choose(s,"enter_live_rescue");assert.equal(s.story.nodeId,"staging");});
test("M3_07 missed quest cannot enter live staging",async()=>{const {engine}=await makeEngine();const v=await engine.present(failed());assert.equal(v.choices.some(c=>c.id==="enter_live_rescue"),false);assert.ok(v.choices.some(c=>c.id==="acknowledge_missed_window"));});
test("M3_07 route assessment has real success/failure state",async()=>{let {engine}=await makeEngine(new SequenceDice([20]));let s=active();s=await engine.choose(s,"enter_live_rescue");s=await engine.choose(s,"assess_access");assert.equal(s.world.flags.ferrox_rescue_route_known,true);({engine}=await makeEngine(new SequenceDice([1])));s=active();s=await engine.choose(s,"enter_live_rescue");s=await engine.choose(s,"assess_access");assert.equal(s.world.flags.ferrox_rescue_route_uncertain,true);});
test("M3_07 coordination unlocks balanced priority",async()=>{const {engine}=await makeEngine(new SequenceDice([20]));let s=active();s=await engine.choose(s,"enter_live_rescue");s=await engine.choose(s,"coordinate_workers");s=await engine.choose(s,"coord_enter");s=await engine.choose(s,"south_to_threshold");s=await engine.choose(s,"stabilize_supports");s=await engine.choose(s,"support_to_priority");const v=await engine.present(s);assert.ok(v.choices.some(c=>c.id==="priority_split"));});
test("M3_07 old-map route requires actual prior knowledge",async()=>{const {engine}=await makeEngine();let s=active();s=await engine.choose(s,"enter_live_rescue");s=await engine.choose(s,"direct_entry");let v=await engine.present(s);assert.ok(v.choices.some(c=>c.id==="use_old_map_route"));delete s.world.flags.old_maps_read;v=await engine.present(s);assert.equal(v.choices.some(c=>c.id==="use_old_map_route"),false);});
test("M3_07 timed action can expire quest before finalization",async()=>{const {engine}=await makeEngine();let s=active(20);s=await engine.choose(s,"enter_live_rescue");s=await engine.choose(s,"direct_entry");s=await engine.choose(s,"stabilize_supports");assert.equal(s.quests.M3_FERROX_RESCUE.status,"failed");assert.equal(s.world.flags.ferrox_rescue_state,"missed");s=await engine.choose(s,"support_to_checkpoint");const v=await engine.present(s);assert.ok(v.choices.some(c=>c.id==="checkpoint_expired"));assert.equal(v.choices.some(c=>c.id==="finalize_stabilized"),false);});
test("M3_07 evacuation finalization completes quest without deciding global casualties",async()=>{const {engine}=await makeEngine();let s=active();s=await engine.choose(s,"enter_live_rescue");s=await engine.choose(s,"direct_entry");s=await engine.choose(s,"push_direct");s=await engine.choose(s,"direct_fail_priority");s=await engine.choose(s,"priority_evacuate");s=await engine.choose(s,"finalize_evacuated");assert.equal(s.quests.M3_FERROX_RESCUE.status,"completed");assert.equal(s.world.flags.ferrox_rescue_state,"evacuation_supported");assert.equal(s.world.flags.ferrox_rescue_outcome_available,true);assert.equal(s.world.flags.ferrox_final_casualties,undefined);});
test("M3_07 support-only route is a legitimate lower-risk outcome",async()=>{const {engine}=await makeEngine();let s=active();s=await engine.choose(s,"enter_live_rescue");s=await engine.choose(s,"direct_entry");s=await engine.choose(s,"threshold_withdraw");s=await engine.choose(s,"partial_report_checkpoint");s=await engine.choose(s,"finalize_support_only");assert.equal(s.world.flags.ferrox_rescue_state,"support_only");assert.equal(s.quests.M3_FERROX_RESCUE.status,"completed");});
test("M3_07 explicit decline fails quest and living-world outcome records declined",async()=>{const {engine}=await makeEngine();let s=active();s=await engine.choose(s,"enter_live_rescue");s=await engine.choose(s,"decline_rescue");assert.equal(s.quests.M3_FERROX_RESCUE.status,"failed");assert.equal(s.quests.M3_FERROX_RESCUE.resolution,"player_declined");assert.equal(s.world.flags.ferrox_rescue_state,"declined");});
test("M3_07 leaving to prepare keeps active quest and advances time",async()=>{const {engine}=await makeEngine();let s=active();const before=s.world.elapsedMinutes;s=await engine.choose(s,"enter_live_rescue");s=await engine.choose(s,"leave_to_prepare");assert.equal(s.quests.M3_FERROX_RESCUE.status,"active");assert.ok(s.world.elapsedMinutes-before>=15);assert.equal(s.story.sceneId,"m03-ferravia-arrival");});
test("M3_07 does not mutate roster, money or rank",async()=>{const {engine}=await makeEngine();let s=active();s.player.money=1000;const roster=structuredClone(s.player.roster);s=await engine.choose(s,"enter_live_rescue");s=await engine.choose(s,"use_known_access");s=await engine.choose(s,"south_to_threshold");assert.equal(s.player.money,1000);assert.deepEqual(s.player.roster,roster);assert.equal(s.competition.rank,"D");});
test("M3_07 re-entry preserves intermediate rescue knowledge",async()=>{const {engine}=await makeEngine(new SequenceDice([20]));let s=active();s=await engine.choose(s,"enter_live_rescue");s=await engine.choose(s,"assess_access");s.story.nodeId="rescue_perimeter";const v=await engine.present(s);assert.equal(v.nodeId,"rescue_perimeter");assert.equal(s.world.flags.ferrox_rescue_route_known,true);});
test("M3_07 state survives save/reload",async()=>{let dir;try{dir=await mkdtemp(path.join(os.tmpdir(),"m307-"));const store=new SaveStore(dir);const {engine}=await makeEngine(new SequenceDice([20]));let s=active();s=await engine.choose(s,"enter_live_rescue");s=await engine.choose(s,"coordinate_workers");s.slot="slot1";await store.save(s);const l=await store.load("slot1");assert.deepEqual(l,s);assert.equal(l.world.flags.ferrox_rescue_coordination,true);}finally{if(dir)await rm(dir,{recursive:true,force:true});}});
