import test from "node:test";
import assert from "node:assert/strict";
import { fileURLToPath } from "node:url";
import { BookgameEngine } from "../src/engine/bookgame-engine.mjs";
import { compileStory } from "../src/compiler/story-compiler.mjs";
import { createNewGameState } from "../src/engine/state.mjs";
import { createPersistentNpc } from "../src/engine/npc-state.mjs";
const scenesDir=fileURLToPath(new URL("../content/scenes/",import.meta.url));
const modulesDir=fileURLToPath(new URL("../content/modules/",import.meta.url));
const eventsDir=fileURLToPath(new URL("../content/events/",import.meta.url));
const ecologyProfilesDir=fileURLToPath(new URL("../content/ecology/",import.meta.url));
const zonePoolsFile=fileURLToPath(new URL("../../campaign/world/ecology/ZONE_POOLS.json",import.meta.url));
const distributionFile=fileURLToPath(new URL("../../campaign/world/ecology/SPECIES_DISTRIBUTION.json",import.meta.url));
const faunaIndexFile=fileURLToPath(new URL("../../campaign/world/fauna/ASTERIA_FAUNA_INDEX.json",import.meta.url));
const ecologyOptions={profilesDir:ecologyProfilesDir,zonePoolsFile,distributionFile,faunaIndexFile};
const fixedNow=()=> "2026-10-05T19:00:00.000Z";
async function makeEngine(){const bundle=await compileStory({scenesDir,modulesDir,eventsDir,ecologyOptions});const scenes={async load(id){return structuredClone(bundle.scenes[id]);},async loadWorldEvents(){return structuredClone(bundle.worldEvents??[]);},async loadEcology(){return structuredClone(bundle.ecology);}};return {engine:new BookgameEngine({scenes,now:fixedNow}),bundle};}
function state(active=true){const s=createNewGameState({protagonist:"Luke",now:fixedNow});s.competition.rank="D";s.competition.rankOrder=2;Object.assign(s.world.flags,{m1_complete:true,m02_unlocked:true,m2_active:true,m2_complete:true,m03_unlocked:true,m3_active:true,ferravia_discovered:true,a3_ferrox_incident_available:true,ferrox_incident_started:true,steven_met:true});s.npcs.Steven=createPersistentNpc({id:"Steven",name:"Steven Stone",state:{introduced:true,role:"technical_observer"}});s.quests.M3_FERROX_RESCUE={id:"M3_FERROX_RESCUE",title:"Emergenza",objective:"Rescue",status:active?"active":"failed",resolution:active?null:"rescue_window_missed",startedAtMinutes:s.world.elapsedMinutes,deadlineAtMinutes:s.world.elapsedMinutes+(active?240:0),resolvedAtMinutes:active?null:s.world.elapsedMinutes,onDeadline:{status:"failed",resolution:"rescue_window_missed",resolvedBy:"world"}};s.story.sceneId="m03-ferrox-incident";s.story.nodeId="incident_alert";s.world.locationId="fer_city_dispatch";return s;}
test("M3_06 compiles and exposes live/late branches",async()=>{const {bundle}=await makeEngine();assert.ok(bundle.scenes["m03-ferrox-incident"].nodes.incident_live);assert.ok(bundle.scenes["m03-ferrox-incident"].nodes.incident_late);});
test("M3_06 live quest exposes live incident only",async()=>{const {engine}=await makeEngine();const v=await engine.present(state(true));assert.ok(v.choices.some(c=>c.id==="read_live_incident"));assert.equal(v.choices.some(c=>c.id==="read_late_incident"),false);});
test("M3_06 expired quest exposes late incident only",async()=>{const {engine}=await makeEngine();const v=await engine.present(state(false));assert.ok(v.choices.some(c=>c.id==="read_late_incident"));assert.equal(v.choices.some(c=>c.id==="read_live_incident"),false);});
test("M3_06 dispatch detail records real information without casualty fabrication",async()=>{const {engine}=await makeEngine();let s=state();s=await engine.choose(s,"read_live_incident");s=await engine.choose(s,"listen_dispatch_details");assert.equal(s.world.flags.ferrox_incident_briefed,true);s=await engine.choose(s,"ask_people_status");s=await engine.choose(s,"people_record");assert.equal(s.world.flags.ferrox_people_at_risk_known,true);assert.equal(s.world.flags.ferrox_rescue_state,undefined);});
test("M3_06 Steven branch is hidden if Steven was never met",async()=>{const {engine}=await makeEngine();let s=state();delete s.world.flags.steven_met;s=await engine.choose(s,"read_live_incident");const v=await engine.present(s);assert.equal(v.choices.some(c=>c.id==="contact_steven_incident"),false);});
test("M3_06 strong prior warning becomes actionable only after Steven confirms its use",async()=>{const {engine}=await makeEngine();let s=state();s.world.flags.ferrox_warning_quality="strong";s=await engine.choose(s,"read_live_incident");s=await engine.choose(s,"contact_steven_incident");const v=await engine.present(s);assert.ok(v.choices.some(c=>c.id==="steven_strong_warning"));s=await engine.choose(s,"steven_strong_warning");s=await engine.choose(s,"strong_to_rescue");assert.equal(s.world.flags.ferrox_preincident_warning_actionable,true);});
test("M3_06 preparing at hub consumes time but leaves rescue quest active",async()=>{const {engine}=await makeEngine();let s=state();const before=s.world.elapsedMinutes;s=await engine.choose(s,"read_live_incident");s=await engine.choose(s,"return_hub_prepare");assert.ok(s.world.elapsedMinutes-before>=15);assert.equal(s.quests.M3_FERROX_RESCUE.status,"active");assert.equal(s.story.sceneId,"m03-ferravia-arrival");});
test("M3_06 can route directly into rescue",async()=>{const {engine}=await makeEngine();let s=state();s=await engine.choose(s,"read_live_incident");s=await engine.choose(s,"go_to_rescue_now");assert.equal(s.story.sceneId,"m03-ferrox-rescue");assert.equal(s.story.nodeId,"rescue_perimeter");});
test("M3_06 late arrival never reopens the failed quest",async()=>{const {engine}=await makeEngine();let s=state(false);s=await engine.choose(s,"read_late_incident");s=await engine.choose(s,"late_go_perimeter");assert.equal(s.quests.M3_FERROX_RESCUE.status,"failed");assert.equal(s.story.sceneId,"m03-ferrox-rescue");});
test("M3_06 does not alter rank or roster",async()=>{const {engine}=await makeEngine();let s=state();const roster=structuredClone(s.player.roster);s=await engine.choose(s,"read_live_incident");s=await engine.choose(s,"call_site_supervisor");s=await engine.choose(s,"site_note_protocol");assert.equal(s.competition.rank,"D");assert.deepEqual(s.player.roster,roster);});
