import test from "node:test";
import assert from "node:assert/strict";
import { fileURLToPath } from "node:url";
import { BookgameEngine } from "../src/engine/bookgame-engine.mjs";
import { compileStory } from "../src/compiler/story-compiler.mjs";
import { createNewGameState } from "../src/engine/state.mjs";
const scenesDir=fileURLToPath(new URL("../content/scenes/",import.meta.url));
const modulesDir=fileURLToPath(new URL("../content/modules/",import.meta.url));
const eventsDir=fileURLToPath(new URL("../content/events/",import.meta.url));
const ecologyProfilesDir=fileURLToPath(new URL("../content/ecology/",import.meta.url));
const zonePoolsFile=fileURLToPath(new URL("../../campaign/world/ecology/ZONE_POOLS.json",import.meta.url));
const distributionFile=fileURLToPath(new URL("../../campaign/world/ecology/SPECIES_DISTRIBUTION.json",import.meta.url));
const faunaIndexFile=fileURLToPath(new URL("../../campaign/world/fauna/ASTERIA_FAUNA_INDEX.json",import.meta.url));
const ecologyOptions={profilesDir:ecologyProfilesDir,zonePoolsFile,distributionFile,faunaIndexFile};
const fixedNow=()=> "2026-10-05T21:00:00.000Z";
async function makeEngine(){const bundle=await compileStory({scenesDir,modulesDir,eventsDir,ecologyOptions});const scenes={async load(id){return structuredClone(bundle.scenes[id]);},async loadWorldEvents(){return structuredClone(bundle.worldEvents??[]);},async loadEcology(){return structuredClone(bundle.ecology);}};return {engine:new BookgameEngine({scenes,now:fixedNow}),bundle};}
function state(friend="Fab",mode="remote",protagonist="Luke"){const s=createNewGameState({protagonist,now:fixedNow});s.competition.rank="D";s.competition.rankOrder=2;Object.assign(s.world.flags,{m1_complete:true,m02_unlocked:true,m2_active:true,m2_complete:true,m03_unlocked:true,m3_active:true,friends_split:true,a3_friend_call_available:true,friend_beat_03_friend_id:friend,friend_beat_03_contact_mode:mode,ferrox_rescue_state:"evacuation_supported",a3_rank_trial_d_c_available:true});s.events.A3_FRIEND_CALL={status:"resolved",outcomeId:"test_seed",firedAtMinutes:s.world.elapsedMinutes};s.story.sceneId="m03-friend-beat-03";s.story.nodeId="friend_call";s.world.locationId="fer_city";return s;}
test("M3_08 compiles a branch for every possible non-player Five member",async()=>{const {bundle}=await makeEngine();const s=bundle.scenes["m03-friend-beat-03"];for(const id of ["luke","mattew","daniel","edward","fab"])assert.ok(s.nodes[id+"_contact"]);});
test("M3_08 dispatch shows only the event-selected friend",async()=>{const {engine}=await makeEngine();const v=await engine.present(state("Fab"));assert.ok(v.choices.some(c=>c.id==="dispatch_fab"));assert.equal(v.choices.some(c=>c.id==="dispatch_mattew"),false);});
test("M3_08 remote contact cannot fabricate physical meeting",async()=>{const {engine}=await makeEngine();let s=state("Fab","remote");s=await engine.choose(s,"dispatch_fab");const v=await engine.present(s);assert.ok(v.choices.some(c=>c.id==="fab_answer_remote"));assert.equal(v.choices.some(c=>c.id==="fab_meet_physical"),false);});
test("M3_08 physical contact uses real event mode",async()=>{const {engine}=await makeEngine();let s=state("Edward","physical");s=await engine.choose(s,"dispatch_edward");const v=await engine.present(s);assert.ok(v.choices.some(c=>c.id==="edward_meet_physical"));assert.equal(v.choices.some(c=>c.id==="edward_answer_remote"),false);});
test("M3_08 rescue debrief is gated by rescue state",async()=>{const {engine}=await makeEngine();let s=state("Daniel");s=await engine.choose(s,"dispatch_daniel");let v=await engine.present(s);assert.ok(v.choices.some(c=>c.id==="daniel_rescue_context"));delete s.world.flags.ferrox_rescue_state;v=await engine.present(s);assert.equal(v.choices.some(c=>c.id==="daniel_rescue_context"),false);});
test("M3_08 honest rescue debrief persists relationship and context",async()=>{const {engine}=await makeEngine();let s=state("Fab");s=await engine.choose(s,"dispatch_fab");s=await engine.choose(s,"fab_rescue_context");const before=s.npcs.Fab.relationship.score;s=await engine.choose(s,"fab_rescue_honest");assert.equal(s.world.flags.friend_beat_03_result,"rescue_honest_debrief");assert.equal(s.npcs.Fab.state.knowsFerroxRescueContext,true);assert.ok(s.npcs.Fab.relationship.score>before);});
test("M3_08 competition exchange does not alter structured rank/trial",async()=>{const {engine}=await makeEngine();let s=state("Mattew");s=await engine.choose(s,"dispatch_mattew");s=await engine.choose(s,"mattew_competition_context");s=await engine.choose(s,"mattew_competition_compare");assert.equal(s.competition.rank,"D");assert.equal(s.competition.trials.RANK_D_TO_C,undefined);});
test("M3_08 close writes required minimum contract",async()=>{const {engine}=await makeEngine();let s=state("Edward");s=await engine.choose(s,"dispatch_edward");s=await engine.choose(s,"edward_answer_remote");s=await engine.choose(s,"edward_remote_brief");s=await engine.choose(s,"close_friend_beat_03");assert.equal(s.world.flags.friend_beat_03_complete,true);assert.equal(s.world.flags.friend_beat_03_friend_id,"Edward");assert.equal(s.world.flags.friend_beat_03_type,"remote_call");assert.equal(s.world.flags.friend_beat_03_result,"remote_brief");});
test("M3_08 scene is inaccessible after completion",async()=>{const {engine}=await makeEngine();const s=state();s.world.flags.friend_beat_03_complete=true;await assert.rejects(()=>engine.present(s),/Scene conditions/);});
test("A3_FRIEND_CALL excludes the protagonist and selects a persistent friend",async()=>{const {engine}=await makeEngine();let s=createNewGameState({protagonist:"Luke",now:fixedNow});s.competition.rank="D";s.competition.rankOrder=2;Object.assign(s.world.flags,{m1_complete:true,m02_unlocked:true,m2_active:true,m2_complete:true,m03_unlocked:true,m3_active:true,ferravia_discovered:true,friends_split:true});s.npcs.Fab.state.fiveRoadsPath="ranger_route";s.story.sceneId="m03-ferravia-arrival";s.story.nodeId="city_hub";s.world.locationId="fer_city";s=await engine.choose(s,"hub_shop");assert.equal(s.events.A3_FRIEND_CALL.status,"resolved");assert.notEqual(s.world.flags.friend_beat_03_friend_id,"Luke");assert.equal(s.world.flags.friend_beat_03_friend_id,"Fab");});
test("M3_08 never mutates roster or money",async()=>{const {engine}=await makeEngine();let s=state("Luke","remote","Fab");s.player.money=777;const roster=structuredClone(s.player.roster);s=await engine.choose(s,"dispatch_luke");s=await engine.choose(s,"luke_answer_remote");s=await engine.choose(s,"luke_remote_brief");assert.equal(s.player.money,777);assert.deepEqual(s.player.roster,roster);});
