import test from "node:test";
import assert from "node:assert/strict";
import { fileURLToPath } from "node:url";
import { BookgameEngine } from "../src/engine/bookgame-engine.mjs";
import { compileStory } from "../src/compiler/story-compiler.mjs";
import { createNewGameState } from "../src/engine/state.mjs";
const scenesDir=fileURLToPath(new URL("../content/scenes/",import.meta.url));
const modulesDir=fileURLToPath(new URL("../content/modules/",import.meta.url));
const eventsDir=fileURLToPath(new URL("../content/events/",import.meta.url));
const ecologyProfilesDir=fileURLToPath(new URL("../content/ecology/",import.meta.url));
const zonePoolsFile=fileURLToPath(new URL("../../campaign/world/ecology/ZONE_POOLS.json",import.meta.url));
const distributionFile=fileURLToPath(new URL("../../campaign/world/ecology/SPECIES_DISTRIBUTION.json",import.meta.url));
const faunaIndexFile=fileURLToPath(new URL("../../campaign/world/fauna/ASTERIA_FAUNA_INDEX.json",import.meta.url));
const ecologyOptions={profilesDir:ecologyProfilesDir,zonePoolsFile,distributionFile,faunaIndexFile};
const fixedNow=()=> "2026-10-05T22:00:00.000Z";
async function makeEngine(){const bundle=await compileStory({scenesDir,modulesDir,eventsDir,ecologyOptions});const scenes={async load(id){return structuredClone(bundle.scenes[id]);},async loadWorldEvents(){return structuredClone(bundle.worldEvents??[]);},async loadEcology(){return structuredClone(bundle.ecology);}};return {engine:new BookgameEngine({scenes,now:fixedNow}),bundle};}
function state(){const s=createNewGameState({protagonist:"Luke",now:fixedNow});s.competition.rank="D";s.competition.rankOrder=2;s.player.trainerLevel=7;Object.assign(s.world.flags,{m1_complete:true,m02_unlocked:true,m2_active:true,m2_complete:true,m03_unlocked:true,m3_active:true,ferravia_discovered:true,a3_crossroads_available:true,ferrox_rescue_state:"evacuation_supported",a3_friend_call_available:true,friend_beat_03_friend_id:"Fab",friend_beat_03_contact_mode:"remote",a3_rank_trial_d_c_available:true});s.story.sceneId="m03-crossroads";s.story.nodeId="crossroads";s.world.locationId="fer_city";return s;}
test("M3_09 compiles canonical priority branches",async()=>{const {bundle}=await makeEngine();const s=bundle.scenes["m03-crossroads"];for(const id of ["rescue_priority","friend_priority","trial_priority","cup_priority","technical_priority","crossroads_close"])assert.ok(s.nodes[id]);});
test("M3_09 rescue priority is hidden without rescue state",async()=>{const {engine}=await makeEngine();const s=state();delete s.world.flags.ferrox_rescue_state;const v=await engine.present(s);assert.equal(v.choices.some(c=>c.id==="review_rescue_priority"),false);});
test("M3_09 friend priority routes to real FRIEND_BEAT_03 instead of completing it automatically",async()=>{const {engine}=await makeEngine();let s=state();s=await engine.choose(s,"review_friend_priority");s=await engine.choose(s,"commit_friend_priority");assert.equal(s.story.sceneId,"m03-friend-beat-03");assert.equal(s.world.flags.a3_crossroads_priority,"friend");assert.equal(s.world.flags.a3_crossroads_complete,true);assert.equal(s.world.flags.friend_beat_03_complete,undefined);});
test("M3_09 Trial priority never registers or promotes",async()=>{const {engine}=await makeEngine();let s=state();s=await engine.choose(s,"review_trial_priority");s=await engine.choose(s,"commit_trial_priority");assert.equal(s.world.flags.a3_crossroads_priority,"trial");assert.equal(s.competition.rank,"D");assert.equal(s.competition.trials.RANK_D_TO_C,undefined);});
test("M3_09 Regional Cup option appears only when canonical event is available",async()=>{const {engine}=await makeEngine();let s=state();let v=await engine.present(s);assert.equal(v.choices.some(c=>c.id==="review_cup_priority"),false);s.world.flags.a3_regional_cup_available=true;v=await engine.present(s);assert.ok(v.choices.some(c=>c.id==="review_cup_priority"));});
test("M3_09 technical priority is always a valid non-competitive choice",async()=>{const {engine}=await makeEngine();let s=state();s=await engine.choose(s,"review_technical_priority");s=await engine.choose(s,"commit_technical_priority");assert.equal(s.world.flags.a3_crossroads_priority,"technical");assert.equal(s.world.flags.a3_crossroads_complete,true);});
test("M3_09 deferral advances time without falsely completing anchor",async()=>{const {engine}=await makeEngine();let s=state();const before=s.world.elapsedMinutes;s=await engine.choose(s,"defer_crossroads");assert.ok(s.world.elapsedMinutes-before>=15);assert.equal(s.world.flags.a3_crossroads_complete,undefined);assert.equal(s.world.flags.a3_crossroads_deferred,true);});
test("M3_09 is idempotently blocked after a priority is committed",async()=>{const {engine}=await makeEngine();let s=state();s=await engine.choose(s,"review_technical_priority");s=await engine.choose(s,"commit_technical_priority");s.story.sceneId="m03-crossroads";s.story.nodeId="crossroads";await assert.rejects(()=>engine.present(s),/Scene conditions/);});
test("A3_CROSSROADS does not fire early at Rank D level 6",async()=>{const {engine}=await makeEngine();let s=createNewGameState({protagonist:"Luke",now:fixedNow});s.competition.rank="D";s.competition.rankOrder=2;s.player.trainerLevel=6;Object.assign(s.world.flags,{m1_complete:true,m02_unlocked:true,m2_active:true,m2_complete:true,m03_unlocked:true,m3_active:true,ferravia_discovered:true});s.story.sceneId="m03-ferravia-arrival";s.story.nodeId="city_hub";s.world.locationId="fer_city";s=await engine.choose(s,"hub_shop");assert.equal(s.events.A3_CROSSROADS,undefined);});
test("A3_CROSSROADS fires at trainer level 7 without changing rank",async()=>{const {engine}=await makeEngine();let s=createNewGameState({protagonist:"Luke",now:fixedNow});s.competition.rank="D";s.competition.rankOrder=2;s.player.trainerLevel=7;Object.assign(s.world.flags,{m1_complete:true,m02_unlocked:true,m2_active:true,m2_complete:true,m03_unlocked:true,m3_active:true,ferravia_discovered:true});s.story.sceneId="m03-ferravia-arrival";s.story.nodeId="city_hub";s.world.locationId="fer_city";s=await engine.choose(s,"hub_shop");assert.equal(s.events.A3_CROSSROADS.status,"resolved");assert.equal(s.world.flags.a3_crossroads_available,true);assert.equal(s.competition.rank,"D");});
