import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { BookgameEngine } from "../src/engine/bookgame-engine.mjs";
import { compileStory } from "../src/compiler/story-compiler.mjs";
import { SaveStore } from "../src/engine/save-store.mjs";
import { createNewGameState } from "../src/engine/state.mjs";
import { SequenceDice } from "../src/engine/dice.mjs";
import { createPersistentNpc } from "../src/engine/npc-state.mjs";

const scenesDir=fileURLToPath(new URL("../content/scenes/",import.meta.url));
const modulesDir=fileURLToPath(new URL("../content/modules/",import.meta.url));
const eventsDir=fileURLToPath(new URL("../content/events/",import.meta.url));
const ecologyProfilesDir=fileURLToPath(new URL("../content/ecology/",import.meta.url));
const zonePoolsFile=fileURLToPath(new URL("../../campaign/world/ecology/ZONE_POOLS.json",import.meta.url));
const distributionFile=fileURLToPath(new URL("../../campaign/world/ecology/SPECIES_DISTRIBUTION.json",import.meta.url));
const faunaIndexFile=fileURLToPath(new URL("../../campaign/world/fauna/ASTERIA_FAUNA_INDEX.json",import.meta.url));
const ecologyOptions={profilesDir:ecologyProfilesDir,zonePoolsFile,distributionFile,faunaIndexFile};
const fixedNow=()=> "2026-10-06T03:00:00.000Z";

async function makeEngine(dice=new SequenceDice([1])){const bundle=await compileStory({scenesDir,modulesDir,eventsDir,ecologyOptions});const scenes={async load(id){return structuredClone(bundle.scenes[id]);},async loadWorldEvents(){return structuredClone(bundle.worldEvents??[]);},async loadEcology(){return structuredClone(bundle.ecology);}};return {engine:new BookgameEngine({scenes,dice,now:fixedNow}),bundle};}
function legal(){const s=createNewGameState({protagonist:"Luke",now:fixedNow});s.competition.rank="C";s.competition.rankOrder=3;s.player.trainerLevel=8;Object.assign(s.world.flags,{m3_complete:true,m04_unlocked:true,m4_active:true,mareasale_discovered:true});s.story.sceneId="m04-port-pressure";s.story.nodeId="pressure_board";s.world.locationId="mar_city_cargo";return s;}
function setClock(s,h){s.world.elapsedMinutes=h*60;s.world.day=1;s.world.minuteOfDay=h*60;s.world.time=h<6?"night":h<12?"morning":h<18?"afternoon":"evening";return s;}

test("M4_04 compiles all pressure and synthesis nodes",async()=>{const {bundle}=await makeEngine();const s=bundle.scenes["m04-port-pressure"];for(const n of ["pressure_board","manifest_clear","seal_specific","worker_queue","reroute_pattern","night_transfer","archie_pressure","pressure_synthesis","pressure_close"])assert.ok(s.nodes[n]);});
test("M4_04 Rank D cannot enter port-pressure scene",async()=>{const {engine}=await makeEngine();const s=legal();s.competition.rank="D";s.competition.rankOrder=2;await assert.rejects(()=>engine.present(s),/Scene conditions/);});
test("M4_04 manifest success records mismatch without declaring smuggling",async()=>{const {engine}=await makeEngine(new SequenceDice([20]));let s=legal();s=await engine.choose(s,"check_manifests");assert.equal(s.story.nodeId,"manifest_clear");assert.equal(s.world.flags.port_manifest_mismatch,true);assert.equal(s.world.flags.smuggling_state,undefined);});
test("M4_04 manifest failure records partial evidence only",async()=>{const {engine}=await makeEngine(new SequenceDice([1]));let s=legal();s=await engine.choose(s,"check_manifests");assert.equal(s.story.nodeId,"manifest_partial");assert.equal(s.world.flags.port_manifest_partial,true);assert.equal(s.world.flags.port_manifest_mismatch,undefined);});
test("M4_04 seal success records timing mismatch",async()=>{const {engine}=await makeEngine(new SequenceDice([20]));let s=legal();s=await engine.choose(s,"watch_seals");assert.equal(s.story.nodeId,"seal_specific");assert.equal(s.world.flags.port_seal_mismatch,true);});
test("M4_04 worker Persuasion has real success and failure branches",async()=>{let {engine}=await makeEngine(new SequenceDice([20]));let s=legal();s=await engine.choose(s,"ask_workers");s=await engine.choose(s,"worker_persuade");assert.equal(s.story.nodeId,"worker_open");assert.equal(s.world.flags.port_worker_specific,true);({engine}=await makeEngine(new SequenceDice([1])));s=legal();s=await engine.choose(s,"ask_workers");s=await engine.choose(s,"worker_persuade");assert.equal(s.story.nodeId,"worker_guarded");assert.equal(s.world.flags.port_worker_guarded,true);});
test("M4_04 night-transfer route is hidden in morning",async()=>{const {engine}=await makeEngine();const s=setClock(legal(),9);const v=await engine.present(s);assert.equal(v.choices.some(c=>c.id==="observe_night_transfer"),false);});
test("M4_04 night-transfer route appears in evening",async()=>{const {engine}=await makeEngine();let s=setClock(legal(),20);let v=await engine.present(s);assert.ok(v.choices.some(c=>c.id==="observe_night_transfer"));s=await engine.choose(s,"observe_night_transfer");s=await engine.choose(s,"night_record");assert.equal(s.world.flags.port_night_transfer_noted,true);});
test("M4_04 Archie callback requires persistent shared context",async()=>{const {engine}=await makeEngine();let s=legal();let v=await engine.present(s);assert.equal(v.choices.some(c=>c.id==="ask_archie_pressure"),false);s.world.flags.archie_met=true;s.npcs.Archie=createPersistentNpc({id:"Archie",name:"Archie",state:{introduced:true,sharedPortPressureContext:true}});v=await engine.present(s);assert.ok(v.choices.some(c=>c.id==="ask_archie_pressure"));});
test("M4_04 Archie callback records criterion but no criminal outcome",async()=>{const {engine}=await makeEngine();let s=legal();s.world.flags.archie_met=true;s.npcs.Archie=createPersistentNpc({id:"Archie",name:"Archie",state:{introduced:true,sharedPortPressureContext:true}});s=await engine.choose(s,"ask_archie_pressure");s=await engine.choose(s,"archie_back");assert.equal(s.world.flags.archie_pressure_callback_used,true);assert.equal(s.world.flags.smuggling_state,undefined);});
test("M4_04 strong synthesis requires converging evidence",async()=>{const {engine}=await makeEngine(new SequenceDice([20,20]));let s=legal();s=await engine.choose(s,"check_manifests");s=await engine.choose(s,"manifest_back");s=await engine.choose(s,"watch_seals");s=await engine.choose(s,"seal_synthesis");let v=await engine.present(s);assert.ok(v.choices.some(c=>c.id==="synthesis_strong"));s=await engine.choose(s,"synthesis_strong");assert.equal(s.world.flags.smuggling_signal_quality,"strong");assert.equal(s.world.flags.port_pressure_complete,true);});
test("M4_04 one real anomaly produces partial not strong synthesis",async()=>{const {engine}=await makeEngine(new SequenceDice([20]));let s=legal();s=await engine.choose(s,"check_manifests");s=await engine.choose(s,"manifest_synthesis");const v=await engine.present(s);assert.ok(v.choices.some(c=>c.id==="synthesis_partial"));assert.equal(v.choices.some(c=>c.id==="synthesis_strong"),false);s=await engine.choose(s,"synthesis_partial");assert.equal(s.world.flags.smuggling_signal_quality,"partial");});
test("M4_04 no evidence allows low-confidence close",async()=>{const {engine}=await makeEngine();let s=legal();s=await engine.choose(s,"synthesize_pressure");const v=await engine.present(s);assert.ok(v.choices.some(c=>c.id==="synthesis_low"));s=await engine.choose(s,"synthesis_low");assert.equal(s.world.flags.smuggling_signal_quality,"low");assert.equal(s.world.flags.port_pressure_complete,true);});
test("M4_04 completion never writes final smuggling_state early",async()=>{const {engine}=await makeEngine();let s=legal();s=await engine.choose(s,"synthesize_pressure");s=await engine.choose(s,"synthesis_low");assert.equal(s.world.flags.smuggling_state,undefined);assert.equal(s.world.flags.port_pressure_complete,true);});
test("M4_04 preserves rank roster money and prior M3 state",async()=>{const {engine}=await makeEngine();let s=legal();s.player.money=555;s.player.roster=[{id:"a",species:"Growlithe"}];s.world.flags.ferrox_rescue_state="balanced_support";const roster=structuredClone(s.player.roster);s=await engine.choose(s,"study_schedule");s=await engine.choose(s,"schedule_back");assert.equal(s.competition.rank,"C");assert.equal(s.player.money,555);assert.deepEqual(s.player.roster,roster);assert.equal(s.world.flags.ferrox_rescue_state,"balanced_support");});
test("M4_04 close returns to Mareasale hub with persistent signal",async()=>{const {engine}=await makeEngine();let s=legal();s=await engine.choose(s,"synthesize_pressure");s=await engine.choose(s,"synthesis_low");s=await engine.choose(s,"close_hub");assert.equal(s.story.sceneId,"m04-mareasale-arrival");assert.equal(s.world.flags.smuggling_signal_quality,"low");});
test("M4_04 state survives save/reload",async()=>{let dir;try{dir=await mkdtemp(path.join(os.tmpdir(),"m404-"));const store=new SaveStore(dir);const {engine}=await makeEngine(new SequenceDice([20]));let s=legal();s=await engine.choose(s,"check_manifests");s.slot="slot1";await store.save(s);const l=await store.load("slot1");assert.deepEqual(l,s);assert.equal(l.world.flags.port_manifest_mismatch,true);}finally{if(dir)await rm(dir,{recursive:true,force:true});}});
