import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { BookgameEngine } from "../src/engine/bookgame-engine.mjs";
import { compileStory } from "../src/compiler/story-compiler.mjs";
import { SaveStore } from "../src/engine/save-store.mjs";
import { createNewGameState } from "../src/engine/state.mjs";
import { SequenceDice } from "../src/engine/dice.mjs";
const scenesDir=fileURLToPath(new URL("../content/scenes/",import.meta.url));
const modulesDir=fileURLToPath(new URL("../content/modules/",import.meta.url));
const eventsDir=fileURLToPath(new URL("../content/events/",import.meta.url));
const ecologyProfilesDir=fileURLToPath(new URL("../content/ecology/",import.meta.url));
const zonePoolsFile=fileURLToPath(new URL("../../campaign/world/ecology/ZONE_POOLS.json",import.meta.url));
const distributionFile=fileURLToPath(new URL("../../campaign/world/ecology/SPECIES_DISTRIBUTION.json",import.meta.url));
const faunaIndexFile=fileURLToPath(new URL("../../campaign/world/fauna/ASTERIA_FAUNA_INDEX.json",import.meta.url));
const ecologyOptions={profilesDir:ecologyProfilesDir,zonePoolsFile,distributionFile,faunaIndexFile};
const fixedNow=()=> "2026-10-06T07:00:00.000Z";
async function makeEngine(dice=new SequenceDice([1])){const bundle=await compileStory({scenesDir,modulesDir,eventsDir,ecologyOptions});const scenes={async load(id){return structuredClone(bundle.scenes[id]);},async loadWorldEvents(){return structuredClone(bundle.worldEvents??[]);},async loadEcology(){return structuredClone(bundle.ecology);}};return {engine:new BookgameEngine({scenes,dice,now:fixedNow}),bundle};}
function base(){const s=createNewGameState({protagonist:"Luke",now:fixedNow});s.competition.rank="C";s.competition.rankOrder=3;s.player.trainerLevel=8;Object.assign(s.world.flags,{m1_complete:true,m2_complete:true,m3_complete:true,m04_unlocked:true,m4_active:true,mareasale_discovered:true});s.world.locationId="mar_city";return s;}
function setClock(s,h,m=0){s.world.elapsedMinutes=h*60+m;s.world.day=1;s.world.minuteOfDay=h*60+m;s.world.time=h<6?"night":h<12?"morning":h<18?"afternoon":"evening";return s;}

function state(friend="Mattew",mode="remote",protagonist="Luke"){const s=createNewGameState({protagonist,now:fixedNow});s.competition.rank="C";s.competition.rankOrder=3;s.player.trainerLevel=8;Object.assign(s.world.flags,{m3_complete:true,m04_unlocked:true,m4_active:true,mareasale_discovered:true,friend_beat_04_available:true,friend_beat_04_friend_id:friend,friend_beat_04_contact_mode:mode,a4_league_reg_available:true,reef_visited:true,smuggling_state:"customs_monitoring"});s.events.M4_FRIEND_CALL={status:"resolved",outcomeId:"test_seed",firedAtMinutes:s.world.elapsedMinutes};s.story.sceneId="m04-friend-beat-04";s.story.nodeId="friend_call";s.world.locationId="mar_city";return s;}
function schedule(s,id,loc){s.npcs[id].schedule={id:"test",locationId:loc,availability:"available",activity:"coast_training",startsAtMinutes:null,endsAtMinutes:null,present:true};return s;}
test("M4_08 compiles branches for all five protagonists",async()=>{const {bundle}=await makeEngine();const s=bundle.scenes["m04-friend-beat-04"];for(const id of ["luke","mattew","daniel","edward","fab"])for(const suffix of ["_contact","_harbor","_coast","_remote_node","_smuggling_node","_reef_node","_league_node"])assert.ok(s.nodes[id+suffix]);});
test("M4_08 dispatch exposes only selected friend",async()=>{const {engine}=await makeEngine();const v=await engine.present(state("Mattew"));assert.ok(v.choices.some(c=>c.id==="dispatch_mattew"));assert.equal(v.choices.some(c=>c.id==="dispatch_fab"),false);});
test("M4_08 remote fallback excludes protagonist",async()=>{const {engine}=await makeEngine();let s=base();s.world.flags.port_pressure_complete=true;s.story.sceneId="m04-mareasale-arrival";s.story.nodeId="city_hub";s=await engine.choose(s,"hub_overlook");assert.equal(s.events.M4_FRIEND_CALL.status,"resolved");assert.notEqual(s.world.flags.friend_beat_04_friend_id,"Luke");assert.equal(s.world.flags.friend_beat_04_friend_id,"Mattew");assert.equal(s.world.flags.friend_beat_04_contact_mode,"remote");});
test("M4_08 selector prefers actually present coast friend",async()=>{const {engine}=await makeEngine();let s=base();s.world.flags.port_pressure_complete=true;s=schedule(s,"Daniel","mar_city");s.story.sceneId="m04-mareasale-arrival";s.story.nodeId="city_hub";s=await engine.choose(s,"hub_overlook");assert.equal(s.world.flags.friend_beat_04_friend_id,"Daniel");assert.equal(s.world.flags.friend_beat_04_contact_mode,"physical");});
test("M4_08 physical harbor choice requires matching schedule",async()=>{const {engine}=await makeEngine();let s=state("Mattew","physical");s=schedule(s,"Mattew","mar_city");s=await engine.choose(s,"dispatch_mattew");let v=await engine.present(s);assert.ok(v.choices.some(c=>c.id==="mattew_meet_harbor"));assert.equal(v.choices.some(c=>c.id==="mattew_remote"),false);});
test("M4_08 remote mode never fabricates physical meeting",async()=>{const {engine}=await makeEngine();let s=state("Edward","remote");s=await engine.choose(s,"dispatch_edward");const v=await engine.present(s);assert.ok(v.choices.some(c=>c.id==="edward_remote"));assert.equal(v.choices.some(c=>c.id==="edward_meet_harbor"),false);assert.equal(v.choices.some(c=>c.id==="edward_meet_coast"),false);});
test("M4_08 honest smuggling debrief persists relationship and context",async()=>{const {engine}=await makeEngine();let s=state("Fab","remote");s=await engine.choose(s,"dispatch_fab");s=await engine.choose(s,"fab_smuggling");const before=s.npcs.Fab.relationship.score;s=await engine.choose(s,"fab_smug_honest");assert.equal(s.world.flags.friend_beat_04_result,"honest_smuggling_debrief");assert.equal(s.npcs.Fab.state.knowsM4SmugglingContext,true);assert.ok(s.npcs.Fab.relationship.score>before);});
test("M4_08 close writes required minimum contract",async()=>{const {engine}=await makeEngine();let s=state("Daniel","remote");s=await engine.choose(s,"dispatch_daniel");s=await engine.choose(s,"daniel_remote");s=await engine.choose(s,"daniel_remote_brief");s=await engine.choose(s,"close_friend_beat_04");assert.equal(s.world.flags.friend_beat_04_complete,true);assert.equal(s.world.flags.friend_beat_04_friend_id,"Daniel");assert.equal(s.world.flags.friend_beat_04_type,"remote_call");assert.equal(s.world.flags.friend_beat_04_result,"remote_brief");});
test("M4_08 competition exchange does not alter Rank or history",async()=>{const {engine}=await makeEngine();let s=state("Mattew","remote");const h=s.competition.history.length;s=await engine.choose(s,"dispatch_mattew");s=await engine.choose(s,"mattew_league");s=await engine.choose(s,"mattew_league_compare");assert.equal(s.competition.rank,"C");assert.equal(s.competition.history.length,h);});
test("M4_08 scene is blocked after completion",async()=>{const {engine}=await makeEngine();const s=state();s.world.flags.friend_beat_04_complete=true;await assert.rejects(()=>engine.present(s),/Scene conditions/);});
test("M4_08 survives save/reload",async()=>{let dir;try{dir=await mkdtemp(path.join(os.tmpdir(),"m408-"));const store=new SaveStore(dir);const {engine}=await makeEngine();let s=state("Mattew","remote");s=await engine.choose(s,"dispatch_mattew");s=await engine.choose(s,"mattew_remote");s=await engine.choose(s,"mattew_remote_deep");s.slot="slot1";await store.save(s);const l=await store.load("slot1");assert.deepEqual(l,s);assert.equal(l.world.flags.friend_beat_04_result,"remote_exchange");}finally{if(dir)await rm(dir,{recursive:true,force:true});}});
